import "./globals.css";

export const metadata = {
  title: "Realtime chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-slate-100 flex flex-col items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
